export const CATEGORIAS = [
  'Anúncios (Facebook ADs)',
  'Aplicativos e Ferramentas',
  'IAs',
  'WhatsApp',
  'Consultorias e Mentorias',
  'Contabilidade',
  'Cursos e Formações',
  'Departamento Pessoal',
  'Doações',
  'Edição de Vídeo',
  'Eletrônicos',
  'Endereço Fiscal',
  'Eventos',
  'Impostos e Tributos',
  'Jurídico',
  'Marketplace',
  'Material de Escritório',
  'Meios de Pagamento',
  'Ofertas',
  'Outros',
  'Pró-labore',
  'Recarga e Chip',
  'Registros e Documentos',
  'Reserva de Caixa',
  'Retirada de Lucro',
  'Sócios',
  'Treinamento e Educação',
  'Expansão',
  'Investimentos Futuros',
  'Coprodução',
  'Produtos',
  'Serviços',
  'Receita Financeira',
] as const;

export const CENTROS_CUSTO = [
  'Anúncios',
  'Cursos e Formações',
  'Funcionários',
  'Jurídico',
  'Outros',
  'Reserva de Caixa',
  'Sócios',
  'Softwares e Ferramentas',
] as const;

export type Categoria = typeof CATEGORIAS[number];
export type CentroCusto = typeof CENTROS_CUSTO[number];
