-- BASELINE — chaves e restrições
--
-- Separado das tabelas de propósito: assim a criação não esbarra em referência
-- circular entre chaves estrangeiras. Depende de 00000000000001_baseline_tabelas.sql.

alter table public.acessos add constraint acessos_pkey PRIMARY KEY (id);
alter table public.acessos add constraint acessos_status_check CHECK ((status = ANY (ARRAY['ativo'::text, 'inativo'::text])));
alter table public.ad_accounts add constraint ad_accounts_account_id_key UNIQUE (account_id);
alter table public.ad_accounts add constraint ad_accounts_pkey PRIMARY KEY (id);
alter table public.ad_accounts add constraint ad_accounts_funil_id_fkey FOREIGN KEY (funil_id) REFERENCES funis(id) ON DELETE SET NULL;
alter table public.ad_accounts add constraint ad_accounts_projeto_id_fkey FOREIGN KEY (projeto_id) REFERENCES ofertas_editores(id) ON DELETE SET NULL;
alter table public.assinaturas add constraint assinaturas_subscription_id_payt_key UNIQUE (subscription_id_payt);
alter table public.assinaturas add constraint assinaturas_pkey PRIMARY KEY (id);
alter table public.assinaturas add constraint assinaturas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id);
alter table public.assinaturas add constraint assinaturas_oferta_id_fkey FOREIGN KEY (oferta_id) REFERENCES ofertas(id);
alter table public.avaliacoes_criativos add constraint avaliacoes_criativos_pkey PRIMARY KEY (id);
alter table public.avaliacoes_criativos add constraint avaliacoes_criativos_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES editores(id) ON DELETE CASCADE;
alter table public.avaliacoes_mensais add constraint avaliacoes_mensais_pkey PRIMARY KEY (id);
alter table public.avaliacoes_mensais add constraint avaliacoes_mensais_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES editores(id) ON DELETE CASCADE;
alter table public.caixa_config add constraint caixa_config_pkey PRIMARY KEY (id);
alter table public.cargos add constraint cargos_nome_setor_key UNIQUE (nome, setor_id);
alter table public.cargos add constraint cargos_pkey PRIMARY KEY (id);
alter table public.cargos add constraint cargos_setor_id_fkey FOREIGN KEY (setor_id) REFERENCES setores(id) ON DELETE SET NULL;
alter table public.checkouts_origem add constraint checkouts_origem_pkey PRIMARY KEY (id);
alter table public.checkouts_origem add constraint ao_menos_um_criterio CHECK (((link_titulo IS NOT NULL) OR (produto_nome IS NOT NULL)));
alter table public.clientes add constraint clientes_cpf_hash_key UNIQUE (cpf_hash);
alter table public.clientes add constraint clientes_pkey PRIMARY KEY (id);
alter table public.conferencias_payt add constraint conferencias_payt_pkey PRIMARY KEY (id);
alter table public.conferencias_payt add constraint conferencias_payt_conferido_por_fkey FOREIGN KEY (conferido_por) REFERENCES auth.users(id);
alter table public.conferencias_payt add constraint periodo_valido CHECK ((periodo_fim >= periodo_ini));
alter table public.configuracoes add constraint configuracoes_chave_key UNIQUE (chave);
alter table public.configuracoes add constraint configuracoes_pkey PRIMARY KEY (id);
alter table public.configuracoes_texto add constraint configuracoes_texto_pkey PRIMARY KEY (chave);
alter table public.copy_rotina_cards add constraint copy_rotina_cards_pkey PRIMARY KEY (id);
alter table public.copy_rotina_cards add constraint copy_rotina_cards_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES perfis(id) ON DELETE SET NULL;
alter table public.copy_rotina_cards add constraint copy_rotina_cards_recorrencia_pai_id_fkey FOREIGN KEY (recorrencia_pai_id) REFERENCES copy_rotina_cards(id) ON DELETE CASCADE;
alter table public.copy_rotina_cards add constraint copy_rotina_cards_recorrencia_tipo_check CHECK ((recorrencia_tipo = ANY (ARRAY['diario'::text, 'semanal'::text, 'mensal'::text])));
alter table public.copytrack_ad_swipe add constraint copytrack_ad_swipe_pkey PRIMARY KEY (id);
alter table public.copytrack_ad_swipe add constraint copytrack_ad_swipe_source_check CHECK ((source = ANY (ARRAY['proprio'::text, 'concorrente'::text, 'referencia'::text])));
alter table public.copytrack_daily_quotes add constraint copytrack_daily_quotes_pkey PRIMARY KEY (id);
alter table public.copytrack_filter_options add constraint copytrack_filter_options_pkey PRIMARY KEY (id);
alter table public.copytrack_hooks add constraint copytrack_hooks_pkey PRIMARY KEY (id);
alter table public.copytrack_offer_tracking add constraint copytrack_offer_tracking_pkey PRIMARY KEY (id);
alter table public.copytrack_offer_tracking add constraint copytrack_offer_tracking_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES copytrack_offers(id) ON DELETE CASCADE;
alter table public.copytrack_offers add constraint copytrack_offers_pkey PRIMARY KEY (id);
alter table public.copytrack_offers add constraint copytrack_offers_status_check CHECK ((status = ANY (ARRAY['monitorando'::text, 'acompanhando'::text, 'descartada'::text])));
alter table public.criativo_campos_opcoes add constraint criativo_campos_opcoes_campo_valor_key UNIQUE (campo, valor);
alter table public.criativo_campos_opcoes add constraint criativo_campos_opcoes_pkey PRIMARY KEY (id);
alter table public.criativo_comentarios add constraint criativo_comentarios_pkey PRIMARY KEY (id);
alter table public.criativo_comentarios add constraint criativo_comentarios_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES perfis(id);
alter table public.criativo_comentarios add constraint criativo_comentarios_criativo_id_fkey FOREIGN KEY (criativo_id) REFERENCES producoes(id) ON DELETE CASCADE;
alter table public.criativo_comentarios add constraint criativo_comentarios_resposta_a_fkey FOREIGN KEY (resposta_a) REFERENCES criativo_comentarios(id);
alter table public.criativo_comentarios add constraint criativo_comentarios_tipo_check CHECK ((tipo = ANY (ARRAY['comentario'::text, 'devolucao'::text, 'sistema'::text])));
alter table public.criativo_historico add constraint criativo_historico_pkey PRIMARY KEY (id);
alter table public.criativo_historico add constraint criativo_historico_criativo_id_fkey FOREIGN KEY (criativo_id) REFERENCES producoes(id) ON DELETE CASCADE;
alter table public.criativo_historico add constraint criativo_historico_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES perfis(id);
alter table public.criativo_historico add constraint criativo_historico_tipo_alteracao_check CHECK ((tipo_alteracao = ANY (ARRAY['criacao'::text, 'fase'::text, 'campo'::text])));
alter table public.criterio_opcoes add constraint criterio_opcoes_pkey PRIMARY KEY (id);
alter table public.criterio_opcoes add constraint criterio_opcoes_criterio_id_fkey FOREIGN KEY (criterio_id) REFERENCES criterios_avaliacao(id) ON DELETE CASCADE;
alter table public.criterios_avaliacao add constraint criterios_avaliacao_chave_key UNIQUE (chave);
alter table public.criterios_avaliacao add constraint criterios_avaliacao_pkey PRIMARY KEY (id);
alter table public.criterios_avaliacao add constraint criterios_avaliacao_categoria_check CHECK ((categoria = ANY (ARRAY['individual'::text, 'grupo'::text, 'meta'::text])));
alter table public.criterios_avaliacao add constraint criterios_avaliacao_tipo_check CHECK ((tipo = ANY (ARRAY['single'::text, 'multi'::text, 'number'::text])));
alter table public.dominios add constraint dominios_pkey PRIMARY KEY (id);
alter table public.dominios add constraint dominios_funil_id_fkey FOREIGN KEY (funil_id) REFERENCES funis(id) ON DELETE SET NULL;
alter table public.editor_comissoes add constraint editor_comissoes_pkey PRIMARY KEY (id);
alter table public.editor_comissoes add constraint editor_comissoes_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES editores(id) ON DELETE CASCADE;
alter table public.editor_folgas add constraint editor_folgas_pkey PRIMARY KEY (id);
alter table public.editor_folgas add constraint editor_folgas_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES editores(id) ON DELETE CASCADE;
alter table public.editor_promocoes add constraint editor_promocoes_pkey PRIMARY KEY (id);
alter table public.editor_promocoes add constraint editor_promocoes_cargo_id_fkey FOREIGN KEY (cargo_id) REFERENCES cargos(id) ON DELETE RESTRICT;
alter table public.editor_promocoes add constraint editor_promocoes_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES editores(id) ON DELETE CASCADE;
alter table public.editores add constraint editores_pkey PRIMARY KEY (id);
alter table public.editores add constraint editores_cargo_id_fkey FOREIGN KEY (cargo_id) REFERENCES cargos(id) ON DELETE SET NULL;
alter table public.editores add constraint editores_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.empresas add constraint empresas_nome_key UNIQUE (nome);
alter table public.empresas add constraint empresas_pkey PRIMARY KEY (id);
alter table public.ferramentas_saas add constraint ferramentas_saas_pkey PRIMARY KEY (id);
alter table public.funil_subofertas add constraint funil_subofertas_funil_id_oferta_id_key UNIQUE (funil_id, oferta_id);
alter table public.funil_subofertas add constraint funil_subofertas_pkey PRIMARY KEY (id);
alter table public.funil_subofertas add constraint funil_subofertas_funil_id_fkey FOREIGN KEY (funil_id) REFERENCES funis(id) ON DELETE CASCADE;
alter table public.funil_subofertas add constraint funil_subofertas_oferta_id_fkey FOREIGN KEY (oferta_id) REFERENCES ofertas(id) ON DELETE CASCADE;
alter table public.funis add constraint funis_pkey PRIMARY KEY (id);
alter table public.funis add constraint funis_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id);
alter table public.funis add constraint funis_oferta_id_fkey FOREIGN KEY (oferta_id) REFERENCES ofertas_editores(id) ON DELETE SET NULL;
alter table public.funis add constraint funis_status_check CHECK ((status = ANY (ARRAY['planejado'::text, 'ativo'::text, 'pausado'::text, 'pausado_analise'::text, 'arquivado'::text])));
alter table public.funis_producao add constraint funis_producao_pkey PRIMARY KEY (funil_id);
alter table public.funis_producao add constraint funis_producao_funil_id_fkey FOREIGN KEY (funil_id) REFERENCES funis(id) ON DELETE CASCADE;
alter table public.funis_producao add constraint funis_producao_status_producao_check CHECK ((status_producao = ANY (ARRAY['em_construcao'::text, 'ativo'::text, 'pausado'::text, 'encerrado'::text])));
alter table public.import_a_20260823 add constraint import_a_20260823_pkey PRIMARY KEY (card_id);
alter table public.links_trafego_sem_utm add constraint links_trafego_sem_utm_pkey PRIMARY KEY (link_titulo);
alter table public.meta_ativos add constraint meta_ativos_pkey PRIMARY KEY (id);
alter table public.meta_ativos add constraint meta_ativos_status_check CHECK ((status = ANY (ARRAY['active'::text, 'paused'::text, 'blocked'::text, 'unknown'::text])));
alter table public.meta_ativos add constraint meta_ativos_tipo_check CHECK ((tipo = ANY (ARRAY['bm'::text, 'ca'::text, 'pixel'::text, 'domain'::text, 'whatsapp'::text, 'fanpage'::text, 'instagram'::text])));
alter table public.meta_insights_raw add constraint meta_insights_raw_ad_account_id_data_nivel_objeto_id_key UNIQUE (ad_account_id, data, nivel, objeto_id);
alter table public.meta_insights_raw add constraint meta_insights_raw_pkey PRIMARY KEY (id);
alter table public.meta_insights_raw add constraint meta_insights_raw_ad_account_id_fkey FOREIGN KEY (ad_account_id) REFERENCES ad_accounts(id) ON DELETE CASCADE;
alter table public.meta_sync_control add constraint meta_sync_control_ad_account_id_key UNIQUE (ad_account_id);
alter table public.meta_sync_control add constraint meta_sync_control_pkey PRIMARY KEY (id);
alter table public.meta_sync_control add constraint meta_sync_control_ad_account_id_fkey FOREIGN KEY (ad_account_id) REFERENCES ad_accounts(id);
alter table public.meta_sync_estado add constraint meta_sync_estado_pkey PRIMARY KEY (ad_account_id);
alter table public.meta_sync_estado add constraint meta_sync_estado_ad_account_id_fkey FOREIGN KEY (ad_account_id) REFERENCES ad_accounts(id) ON DELETE CASCADE;
alter table public.metricas_diarias add constraint metricas_diarias_data_produto_key UNIQUE (data, produto);
alter table public.metricas_diarias add constraint metricas_diarias_pkey PRIMARY KEY (id);
alter table public.metricas_meta add constraint metricas_meta_pkey PRIMARY KEY (id);
alter table public.metricas_meta add constraint metricas_meta_ad_account_id_fkey FOREIGN KEY (ad_account_id) REFERENCES ad_accounts(id);
alter table public.notas_fiscais add constraint notas_fiscais_pkey PRIMARY KEY (id);
alter table public.notas_fiscais add constraint notas_fiscais_ferramenta_id_fkey FOREIGN KEY (ferramenta_id) REFERENCES ferramentas_saas(id);
alter table public.notificacoes add constraint notificacoes_pkey PRIMARY KEY (id);
alter table public.notificacoes add constraint notificacoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notion_criativos add constraint notion_criativos_pkey PRIMARY KEY (id);
alter table public.ofertas add constraint ofertas_code_payt_key UNIQUE (code_payt);
alter table public.ofertas add constraint ofertas_pkey PRIMARY KEY (id);
alter table public.ofertas_editores add constraint ofertas_editores_pkey PRIMARY KEY (id);
alter table public.ofertas_editores add constraint ofertas_editores_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE SET NULL;
alter table public.payt_webhook_raw add constraint payt_webhook_raw_pkey PRIMARY KEY (id);
alter table public.perfis add constraint perfis_pkey PRIMARY KEY (id);
alter table public.perfis add constraint perfis_cargo_id_fkey FOREIGN KEY (cargo_id) REFERENCES cargos(id) ON DELETE SET NULL;
alter table public.perfis add constraint perfis_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.perfis add constraint perfis_setor_id_fkey FOREIGN KEY (setor_id) REFERENCES setores(id) ON DELETE SET NULL;
alter table public.permissoes_paginas add constraint permissoes_paginas_usuario_id_pagina_key UNIQUE (usuario_id, pagina);
alter table public.permissoes_paginas add constraint permissoes_paginas_pkey PRIMARY KEY (id);
alter table public.permissoes_paginas add constraint permissoes_paginas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.processos_artigos add constraint processos_artigos_pkey PRIMARY KEY (id);
alter table public.processos_artigos add constraint processos_artigos_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id);
alter table public.processos_artigos add constraint processos_artigos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES processos_categorias(id) ON DELETE CASCADE;
alter table public.processos_artigos add constraint processos_artigos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id);
alter table public.processos_categorias add constraint processos_categorias_pkey PRIMARY KEY (id);
alter table public.producao_membros add constraint producao_membros_perfil_id_key UNIQUE (perfil_id);
alter table public.producao_membros add constraint producao_membros_pkey PRIMARY KEY (id);
alter table public.producao_membros add constraint producao_membros_perfil_id_fkey FOREIGN KEY (perfil_id) REFERENCES perfis(id) ON DELETE CASCADE;
alter table public.producao_membros add constraint producao_membros_nivel_check CHECK ((nivel = ANY (ARRAY['socio'::text, 'lider'::text, 'membro'::text])));
alter table public.producao_membros add constraint producao_membros_setor_check CHECK ((setor = ANY (ARRAY['edicao'::text, 'copy'::text, 'trafego'::text, 'projetos'::text])));
alter table public.producoes add constraint criativos_pkey PRIMARY KEY (id);
alter table public.producoes add constraint criativos_copy_id_fkey FOREIGN KEY (copy_id) REFERENCES perfis(id);
alter table public.producoes add constraint criativos_funil_id_fkey FOREIGN KEY (funil_id) REFERENCES funis(id);
alter table public.producoes add constraint criativos_gestor_id_fkey FOREIGN KEY (gestor_id) REFERENCES perfis(id);
alter table public.producoes add constraint criativos_projeto_id_fkey FOREIGN KEY (projeto_id) REFERENCES ofertas_editores(id) ON DELETE SET NULL;
alter table public.producoes add constraint criativos_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES perfis(id);
alter table public.producoes add constraint criativos_variacao_de_fkey FOREIGN KEY (variacao_de) REFERENCES producoes(id);
alter table public.producoes add constraint producoes_especialista_id_fkey FOREIGN KEY (especialista_id) REFERENCES perfis(id);
alter table public.producoes add constraint criativos_tipo_check CHECK ((tipo = ANY (ARRAY['criativo'::text, 'vsl'::text, 'aula'::text])));
alter table public.producoes add constraint status_veiculacao_conhecido CHECK (((status_veiculacao IS NULL) OR (status_veiculacao = ANY (ARRAY['Rodando'::text, 'Pausado'::text, 'Encerrado'::text, 'Bloqueado'::text, 'Arquivado'::text]))));
alter table public.radar_areas add constraint radar_areas_slug_key UNIQUE (slug);
alter table public.radar_areas add constraint radar_areas_pkey PRIMARY KEY (id);
alter table public.radar_testes add constraint radar_testes_pkey PRIMARY KEY (id);
alter table public.radar_testes add constraint radar_testes_area_id_fkey FOREIGN KEY (area_id) REFERENCES radar_areas(id) ON DELETE SET NULL;
alter table public.radar_testes add constraint radar_testes_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id);
alter table public.radar_testes add constraint radar_testes_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.radar_testes add constraint radar_testes_deletado_por_fkey FOREIGN KEY (deletado_por) REFERENCES auth.users(id);
alter table public.radar_testes add constraint radar_testes_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.referencias add constraint referencias_pkey PRIMARY KEY (id);
alter table public.referencias add constraint referencias_area_id_fkey FOREIGN KEY (area_id) REFERENCES radar_areas(id) ON DELETE SET NULL;
alter table public.referencias add constraint referencias_atualizado_por_fkey FOREIGN KEY (atualizado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.referencias add constraint referencias_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.referencias add constraint referencias_deletado_por_fkey FOREIGN KEY (deletado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.regras_categoria add constraint regras_categoria_pkey PRIMARY KEY (id);
alter table public.setor_permissoes add constraint setor_permissoes_pkey PRIMARY KEY (setor_id, pagina);
alter table public.setor_permissoes add constraint setor_permissoes_setor_id_fkey FOREIGN KEY (setor_id) REFERENCES setores(id) ON DELETE CASCADE;
alter table public.setores add constraint setores_pkey PRIMARY KEY (id);
alter table public.testes_funis add constraint testes_funis_pkey PRIMARY KEY (id);
alter table public.testes_funis add constraint testes_funis_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES auth.users(id);
alter table public.testes_funis add constraint testes_funis_funil_id_fkey FOREIGN KEY (funil_id) REFERENCES funis(id) ON DELETE CASCADE;
alter table public.testes_funis add constraint testes_funis_radar_teste_id_fkey FOREIGN KEY (radar_teste_id) REFERENCES radar_testes(id) ON DELETE SET NULL;
alter table public.testes_funis add constraint testes_funis_dificuldade_check CHECK ((dificuldade = ANY (ARRAY['facil'::text, 'media'::text, 'dificil'::text])));
alter table public.testes_funis add constraint testes_funis_funil_required_non_ad CHECK (((tipo = 'ad'::text) OR (funil_id IS NOT NULL)));
alter table public.testes_funis add constraint testes_funis_impacto_check CHECK ((impacto = ANY (ARRAY['alto'::text, 'medio'::text, 'baixo'::text])));
alter table public.testes_funis add constraint testes_funis_pipeline_status_check CHECK ((pipeline_status = ANY (ARRAY['planejado'::text, 'produzindo'::text, 'pronto_para_teste'::text, 'rodando'::text, 'concluido'::text])));
alter table public.testes_funis add constraint testes_funis_tipo_check CHECK ((tipo = ANY (ARRAY['funil_novo'::text, 'ab_interno'::text, 'ad'::text])));
alter table public.testes_funis add constraint testes_funis_vencedor_check CHECK (((vencedor = ANY (ARRAY['a'::text, 'b'::text, 'inconclusivo'::text])) OR (vencedor IS NULL)));
alter table public.transacoes add constraint transacoes_referencia_externa_unique UNIQUE (referencia_externa);
alter table public.transacoes add constraint transacoes_pkey PRIMARY KEY (id);
alter table public.utm_links add constraint utm_links_pkey PRIMARY KEY (id);
alter table public.utm_links add constraint utm_links_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES perfis(id) ON DELETE SET NULL;
alter table public.utm_links add constraint utm_links_projeto_id_fkey FOREIGN KEY (projeto_id) REFERENCES ofertas_editores(id) ON DELETE SET NULL;
alter table public.venda_itens add constraint venda_itens_pkey PRIMARY KEY (id);
alter table public.venda_itens add constraint venda_itens_oferta_id_fkey FOREIGN KEY (oferta_id) REFERENCES ofertas(id);
alter table public.venda_itens add constraint venda_itens_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE CASCADE;
alter table public.vendas add constraint vendas_pedido_id_key UNIQUE (pedido_id);
alter table public.vendas add constraint vendas_pkey PRIMARY KEY (id);
alter table public.vendas add constraint vendas_ad_account_id_fkey FOREIGN KEY (ad_account_id) REFERENCES ad_accounts(id);
alter table public.vendas add constraint vendas_assinatura_id_fkey FOREIGN KEY (assinatura_id) REFERENCES assinaturas(id);
alter table public.vendas add constraint vendas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id);
alter table public.vendas add constraint vendas_funil_id_fkey FOREIGN KEY (funil_id) REFERENCES funis(id) ON DELETE SET NULL;
alter table public.vendas add constraint vendas_upsell_de_fkey FOREIGN KEY (upsell_de) REFERENCES vendas(id);
alter table public.vendas_hotmart add constraint vendas_hotmart_hotmart_id_key UNIQUE (hotmart_id);
alter table public.vendas_hotmart add constraint vendas_hotmart_pkey PRIMARY KEY (id);
alter table public.vendas_payt add constraint vendas_payt_payt_id_key UNIQUE (payt_id);
alter table public.vendas_payt add constraint vendas_payt_pkey PRIMARY KEY (id);